//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_board.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblKart
    {
        [Display(Name ="Kart Numarası")]
        [Required(ErrorMessage ="Lütfen bir kart numarası giriniz !")]
        [Range(1,9999999,ErrorMessage = "Kart numarası 1 ile 9999999 arasınada değerler alabilir !")]
        public int kartID { get; set; }
        [Display(Name = "Teknik Uzman Adı")]
        [Required(ErrorMessage ="Teknik Uzman seçimi zorunlu bir alandır !")]
        public Nullable<int> personelID { get; set; }
        [Display(Name ="Proje Adı")]
        [Required(ErrorMessage ="Proje seçimi zorunlu bir alandır !")]
        public Nullable<int> projeID { get; set; }
        public Nullable<int> durumID { get; set; }
        [Display(Name ="Kart Oluşturulma Tarihi")]
        public Nullable<System.DateTime> tarih { get; set; }
        [Display(Name = "Tahmini Gerçekleşme Süresi")]
        public string tahminiSure { get; set; }
        [Display(Name = "Kartın Gerçekleşme Süresi")]
        [StringLength(15,ErrorMessage ="Hatalı veri girişi !")]
        public string gerceklesenSure { get; set; }
        [Display(Name ="Açıklama")]
        [Required(ErrorMessage ="Açıklama zorunlu bir alandır !")]
        [StringLength(250,ErrorMessage ="Açıklama çok fazla karakter içeriyor !")]
        public string aciklama { get; set; }
        [Display(Name ="Notlar")]
        [StringLength(250,ErrorMessage ="Not çok fazla karakter içeriyor !")]
        public string notlar { get; set; }
        [Display(Name ="İş Takibi")]
        public string işTakibi { get; set; }
    
        public virtual tblDurum tblDurum { get; set; }
        public virtual tblPersonel tblPersonel { get; set; }
        public virtual tblProje tblProje { get; set; }
    }
}
